# Generated by Django 3.1.4 on 2020-12-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersMailing',
        ),
    ]
