# Generated by Django 3.1.4 on 2020-12-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1985, verbose_name='Время отправки'),
            preserve_default=False,
        ),
    ]
