# Generated by Django 3.1.4 on 2021-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210202_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='image_file',
            field=models.ImageField(default='', upload_to='send_images', verbose_name='Картинка'),
        ),
    ]
