# Generated by Django 3.1.4 on 2021-02-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_messages_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image_file',
            field=models.ImageField(default='', upload_to='images', verbose_name='Картинка'),
        ),
    ]
