# Generated by Django 3.1.4 on 2021-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210215_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image_file',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
